spring:
  application:
    name: lending-service

credito:
  security:
    resource-server:
      audiences:
        - credito-api
        - credito-admin-api
      issuers:
        - issuer-uri: ${CUSTOMER_REALM_ISSUER_URI}
          jwk-set-uri: ${CUSTOMER_REALM_JWK_SET_URI}
        - issuer-uri: ${CUSTOMER_REALM_INTERNAL_ISSUER_URI}
          jwk-set-uri: ${CUSTOMER_REALM_INTERNAL_JWK_SET_URI}
        - issuer-uri: ${ADMIN_REALM_ISSUER_URI}
          jwk-set-uri: ${ADMIN_REALM_JWK_SET_URI}
        - issuer-uri: ${ADMIN_REALM_INTERNAL_ISSUER_URI}
          jwk-set-uri: ${ADMIN_REALM_INTERNAL_JWK_SET_URI}

server:
  port: ${SERVER_PORT}
  ssl:
    enabled: ${MTLS_ENABLED:false}
    key-store: ${MTLS_KEY_STORE:}
    key-store-password: ${MTLS_KEY_STORE_PASSWORD:}
    key-store-type: ${MTLS_KEY_STORE_TYPE:PKCS12}
    trust-store: ${MTLS_TRUST_STORE:}
    trust-store-password: ${MTLS_TRUST_STORE_PASSWORD:}
    trust-store-type: ${MTLS_TRUST_STORE_TYPE:PKCS12}
    client-auth: ${MTLS_CLIENT_AUTH:none}

management:
  endpoints:
    web:
      exposure:
        include: health,info
