spring:
  application:
    name: batch-service
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: embedded

server:
  port: ${SERVER_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info
