#!/bin/sh
set -eu

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS \`${KC_DB_URL_DATABASE}\`;
CREATE USER IF NOT EXISTS '${KC_DB_USERNAME}'@'%' IDENTIFIED BY '${KC_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${KC_DB_URL_DATABASE}\`.* TO '${KC_DB_USERNAME}'@'%';
FLUSH PRIVILEGES;
SQL
